// Manifest portfolio — GENEROWANY automatycznie przez scripts/gen-portfolio-manifest.mjs.
// Nie edytuj ręcznie. Dodajesz pracę: wrzut do ~/Desktop/portfolio ->
// `bash scripts/optimize-portfolio.sh` -> `node scripts/gen-portfolio-manifest.mjs`.

export type PortfolioItem = {
  kind: "image" | "video";
  src: string;
  poster?: string; // tylko video
  width: number;
  height: number;
  alt: string;
};

export const portfolioItems: PortfolioItem[] = [
  {
    kind: "image",
    src: "/portfolio/img/technology-integration-visuals-43950.webp",
    width: 2752,
    height: 1536,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/filip-ai-coach-1-5.mp4",
    poster: "/portfolio/poster/filip-ai-coach-1-5.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
  {
    kind: "video",
    src: "/portfolio/video/screen-recording-2026-06-07-at-09-32-54.mp4",
    poster: "/portfolio/poster/screen-recording-2026-06-07-at-09-32-54.webp",
    width: 1280,
    height: 708,
    alt: "Projekt (wideo)",
  },
  {
    kind: "video",
    src: "/portfolio/video/filip-ai-coach-2-90.mp4",
    poster: "/portfolio/poster/filip-ai-coach-2-90.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/cinematic-medium-wide-tracking-shot-following-a-single-operat-e90c0e93-5108-4559-9da8-4c6e92b5b1de-0.webp",
    width: 2880,
    height: 1614,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/yt-p7s8qayubnw-21-dni-w-tokyo-studia-w-japonii-w-wieku.mp4",
    poster: "/portfolio/poster/yt-p7s8qayubnw-21-dni-w-tokyo-studia-w-japonii-w-wieku.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/cinematic-first-person-pov-wide-environmental-shot-walking-th-d24b8285-28aa-4080-93b3-da13cb28c182-2.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/anamorphic-2-391-letterbox-crop-medium-close-up-stylized-illu-7fe6ac8c-9d71-43e0-a56e-42e1c9d1bcb6-1.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-4.webp",
    width: 2400,
    height: 1792,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/medium-close-up-24mm-anamorphic-stylized-illustrated-cabin-sh-53e04643-e3e3-477f-85d6-aa243fc87d84-3.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/high-angle-birds-eye-wide-shot-looking-down-into-the-neo-mali-baa494c7-9b5b-4112-b6d9-f4f1f54b85d4-3.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/wojtek-elevator-talks-reel.mp4",
    poster: "/portfolio/poster/wojtek-elevator-talks-reel.webp",
    width: 1080,
    height: 1920,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/wide-cinematic-still-anamorphic-2-391-letterbox-crop-shown-fr-c76f77f9-b6ff-4070-b9c5-c7782a22a854-0.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/yt-muzk8crnvog-pov-japo-scy-przyjaciele-zaprosili-mni.mp4",
    poster: "/portfolio/poster/yt-muzk8crnvog-pov-japo-scy-przyjaciele-zaprosili-mni.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/extreme-macro-closeup-visuals.webp",
    width: 2752,
    height: 1536,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/gta-angle.mp4",
    poster: "/portfolio/poster/gta-angle.webp",
    width: 1080,
    height: 1920,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/cinematic-medium-wide-strategy-session-shot-inside-the-neo-ma-f7b1d53c-ff0e-4262-95b8-fb2e3cf3ae21-1.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/cinematic-wide-environmental-shot-of-a-futuristic-academy-wel-355a19e7-a268-4bf8-b568-78f467a4bf8f-0.webp",
    width: 2880,
    height: 1614,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/senior-brand-magnific-ai.webp",
    width: 2048,
    height: 2048,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-ai-7.webp",
    width: 2752,
    height: 1536,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/low-angle-closeup-visuals.webp",
    width: 2752,
    height: 1536,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/medium-closeup-portrait-23-year-old.webp",
    width: 2752,
    height: 1536,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-2.webp",
    width: 2880,
    height: 1472,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-6.webp",
    width: 2880,
    height: 2880,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-ai-1.webp",
    width: 1856,
    height: 2304,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/ayla-branding-os.mp4",
    poster: "/portfolio/poster/ayla-branding-os.webp",
    width: 1080,
    height: 1920,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/wide-angle-eye-level-anamorphic-2-391-medium-close-up-of-a-si-439851a8-dae8-4dce-b721-48b21368c2e7-3.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-3.webp",
    width: 1856,
    height: 2304,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/wide-environmental-stylized-illustrated-cinematic-still-anamo-ca215b9e-5cf7-4068-a49f-840f522d26f1-3.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/cinematic-medium-wide-environmental-game-engine-character-sho-41edb583-0e96-4cac-a5d2-b7ff12189f8e-2.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-5.webp",
    width: 2880,
    height: 840,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/cinematic-ultra-wide-environmental-game-engine-character-shot-3fe26830-b731-4c79-b864-474451b00d64-1.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/yt-ps1jnim0a10-jak-naprawd-wygl-da-ycie-studenta-w-toki.mp4",
    poster: "/portfolio/poster/yt-ps1jnim0a10-jak-naprawd-wygl-da-ycie-studenta-w-toki.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/eye-level-medium-shot-anamorphic-35-50mm-stylized-illustrated-29f7bf80-920e-4481-99b1-c8c9efd79082-1.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/eye-level-medium-tight-anamorphic-stylized-illustrated-vlog-s-0aae579a-132c-497d-b49f-6dc822461b62-0.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/high-contrast-black-and-white-still.webp",
    width: 2752,
    height: 1536,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-ai-6.webp",
    width: 2752,
    height: 1536,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/low-rear-mounted-pov-anamorphic-wide-angle-14-24mm-symmetrica-920f312f-2a3a-4ee5-9a31-82fe7a1b9c8d-2.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/cinematic-wide-environmental-shot-of-a-single-solo-operator-s-865b55da-94e5-485d-976e-1eafa78ad7ef-3.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-ai-2.webp",
    width: 2432,
    height: 1760,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/magnific-upscale-and-enhance-this-aqpzclmfsh.webp",
    width: 1792,
    height: 2400,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/low-near-water-level-cinematic-still-anamorphic-2-39-50mm-tel-e9dd6ad2-6622-430f-8968-fdaef8ccc159-1.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/screen-recording-2024-12-08-at-09-34-26.mp4",
    poster: "/portfolio/poster/screen-recording-2024-12-08-at-09-34-26.webp",
    width: 1280,
    height: 800,
    alt: "Projekt (wideo)",
  },
  {
    kind: "video",
    src: "/portfolio/video/petite-pants-test-reel.mp4",
    poster: "/portfolio/poster/petite-pants-test-reel.webp",
    width: 1280,
    height: 2276,
    alt: "Projekt (wideo)",
  },
  {
    kind: "video",
    src: "/portfolio/video/yt-ranz5agoku4-pov-jako-21-latek-balansujesz-prac-stu.mp4",
    poster: "/portfolio/poster/yt-ranz5agoku4-pov-jako-21-latek-balansujesz-prac-stu.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
  {
    kind: "video",
    src: "/portfolio/video/yt-1yktxhy2m2y-ai-zmieni-wszystko-buduj-biznes-z-ai-w.mp4",
    poster: "/portfolio/poster/yt-1yktxhy2m2y-ai-zmieni-wszystko-buduj-biznes-z-ai-w.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-ai.webp",
    width: 1792,
    height: 2400,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/slightly-below-eye-level-extreme-wide-angle-10-14mm-fisheye-a-fa297512-f907-4f11-a33c-59faf13b6824-1.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/magnific-ai-image.webp",
    width: 1792,
    height: 2400,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/screen-recording-2026-06-07-at-09-32-11.mp4",
    poster: "/portfolio/poster/screen-recording-2026-06-07-at-09-32-11.webp",
    width: 1280,
    height: 708,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/localhost-3001-high-res-1-copy-2.webp",
    width: 2880,
    height: 1620,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/yt-qz6vg0z1wo4-moje-ostatnie-100-dni-w-japonii-i-najdzi.mp4",
    poster: "/portfolio/poster/yt-qz6vg0z1wo4-moje-ostatnie-100-dni-w-japonii-i-najdzi.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
  {
    kind: "video",
    src: "/portfolio/video/skolim-jbb-full-1.mp4",
    poster: "/portfolio/poster/skolim-jbb-full-1.webp",
    width: 1080,
    height: 1920,
    alt: "Projekt (wideo)",
  },
  {
    kind: "video",
    src: "/portfolio/video/screen-recording-2024-12-08-at-11-31-15.mp4",
    poster: "/portfolio/poster/screen-recording-2024-12-08-at-11-31-15.webp",
    width: 1280,
    height: 800,
    alt: "Projekt (wideo)",
  },
  {
    kind: "video",
    src: "/portfolio/video/screen-recording-2024-12-08-at-14-12-23.mp4",
    poster: "/portfolio/poster/screen-recording-2024-12-08-at-14-12-23.webp",
    width: 1280,
    height: 800,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-ai-4.webp",
    width: 2080,
    height: 2048,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/screen-recording-2026-06-07-at-09-31-38.mp4",
    poster: "/portfolio/poster/screen-recording-2026-06-07-at-09-31-38.webp",
    width: 1280,
    height: 708,
    alt: "Projekt (wideo)",
  },
  {
    kind: "video",
    src: "/portfolio/video/yt-r3uwbpfcres-rzeczywisto-przeprowadzki-do-japonii-w-w.mp4",
    poster: "/portfolio/poster/yt-r3uwbpfcres-rzeczywisto-przeprowadzki-do-japonii-w-w.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
  {
    kind: "image",
    src: "/portfolio/img/young-man-traversing-visual.webp",
    width: 2752,
    height: 1536,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/seated-eye-level-medium-wide-anamorphic-35-50mm-shot-of-muscu-a8f1f2e1-387c-4d89-9e4f-c8071c1d876f-0.webp",
    width: 1456,
    height: 816,
    alt: "Projekt",
  },
  {
    kind: "image",
    src: "/portfolio/img/skin-enhancement-magnific-1.webp",
    width: 1792,
    height: 2400,
    alt: "Projekt",
  },
  {
    kind: "video",
    src: "/portfolio/video/yt-60zh6qeno2y-pov-masz-21-lat-i-sam-studiujesz-w-jap.mp4",
    poster: "/portfolio/poster/yt-60zh6qeno2y-pov-masz-21-lat-i-sam-studiujesz-w-jap.webp",
    width: 1280,
    height: 720,
    alt: "Projekt (wideo)",
  },
];
